"""Myxo CLI — uv + typer entrypoint."""

from pathlib import Path

import typer

app = typer.Typer(
    name="myxo",
    help="Myxo — AI Agent Infrastructure Platform.",
)

_DEFAULT_CONFIG = '# Myxo repository configuration\nversion: "0.1"\n'
_DEFAULT_RULES = "# Myxo Rules\n"
_SUBDIRS = ("protocols", "procedures", "pseudopods")


@app.command()
def init() -> None:
    """Initialize a new .myxo/ configuration in the current repository."""
    myxo_dir = Path.cwd() / ".myxo"

    if myxo_dir.exists():
        if not myxo_dir.is_dir():
            typer.echo(".myxo exists but is not a directory. Please remove or rename it before running `myxo init`.")
            raise typer.Exit(code=1)
        typer.echo(".myxo/ already exists — skipping initialization.")
        return

    myxo_dir.mkdir()

    (myxo_dir / "config.yaml").write_text(_DEFAULT_CONFIG)
    (myxo_dir / "rules.md").write_text(_DEFAULT_RULES)

    for subdir in _SUBDIRS:
        sub = myxo_dir / subdir
        sub.mkdir()
        (sub / ".gitkeep").touch()


_AUTOGEN_HEADER = "<!-- Auto-generated by myxo sync. Do not edit manually. -->"


@app.command()
def sync() -> None:
    """Sync agent configurations (Claude Code / Codex / Cursor)."""
    myxo_dir = Path.cwd() / ".myxo"

    if not myxo_dir.is_dir():
        typer.echo("Error: .myxo/ directory not found. Run `myxo init` first.")
        raise typer.Exit(code=1)

    parts: list[str] = [_AUTOGEN_HEADER, ""]

    # Include rules.md (required)
    rules_path = myxo_dir / "rules.md"
    if not rules_path.is_file():
        typer.echo("Error: .myxo/rules.md not found. Run `myxo init` or create .myxo/rules.md.")
        raise typer.Exit(code=1)
    parts.append(rules_path.read_text(encoding="utf-8"))

    # Include all .md files from protocols/
    protocols_dir = myxo_dir / "protocols"
    if protocols_dir.is_dir():
        for md_file in sorted(protocols_dir.glob("*.md")):
            parts.append(md_file.read_text(encoding="utf-8"))

    output = Path.cwd() / "CLAUDE.md"
    output.write_text("\n".join(parts), encoding="utf-8")
    typer.echo(f"CLAUDE.md generated ({output})")


@app.command()
def verify() -> None:
    """Verify GitHub settings match .myxo/ configuration."""
    typer.echo("myxo verify: not yet implemented")
