"""MyxoSyncer — multi-target sync engine for .myxo/ configurations."""

from __future__ import annotations

import abc
from pathlib import Path

_AUTOGEN_HEADER = "<!-- Auto-generated by myxo sync. Do not edit manually. -->"


class Converter(abc.ABC):
    """Base class for target-specific converters."""

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Target name (e.g. 'claude', 'codex')."""

    @abc.abstractmethod
    def output_path(self, root: Path) -> Path:
        """Return the output file path relative to root."""

    def convert(self, content: str) -> str:
        """Convert collected content to target format."""
        return f"{_AUTOGEN_HEADER}\n\n{content}"

    def write(self, root: Path, content: str) -> Path:
        """Write converted content to the target file."""
        path = self.output_path(root)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.convert(content), encoding="utf-8")
        return path


class ClaudeConverter(Converter):
    """Generates CLAUDE.md for Claude Code."""

    @property
    def name(self) -> str:
        return "claude"

    def output_path(self, root: Path) -> Path:
        return root / "CLAUDE.md"


class CodexConverter(Converter):
    """Generates AGENTS.md for Codex."""

    @property
    def name(self) -> str:
        return "codex"

    def output_path(self, root: Path) -> Path:
        return root / "AGENTS.md"


class CursorConverter(Converter):
    """Generates .cursor/rules for Cursor."""

    @property
    def name(self) -> str:
        return "cursor"

    def output_path(self, root: Path) -> Path:
        return root / ".cursor" / "rules"


class WindsurfConverter(Converter):
    """Generates .windsurfrules for Windsurf."""

    @property
    def name(self) -> str:
        return "windsurf"

    def output_path(self, root: Path) -> Path:
        return root / ".windsurfrules"


_CONVERTERS: list[Converter] = [
    ClaudeConverter(),
    CodexConverter(),
    CursorConverter(),
    WindsurfConverter(),
]

_CONVERTER_MAP: dict[str, Converter] = {c.name: c for c in _CONVERTERS}


class MyxoSyncer:
    """Orchestrates syncing .myxo/ content to multiple AI tool targets."""

    def __init__(self, myxo_dir: Path) -> None:
        self._myxo_dir = myxo_dir

    def collect(self) -> str:
        """Collect and concatenate content from .myxo/ directory."""
        parts: list[str] = []

        rules_path = self._myxo_dir / "rules.md"
        if rules_path.is_file():
            parts.append(rules_path.read_text(encoding="utf-8"))

        protocols_dir = self._myxo_dir / "protocols"
        if protocols_dir.is_dir():
            for md_file in sorted(protocols_dir.glob("*.md")):
                parts.append(md_file.read_text(encoding="utf-8"))

        return "\n".join(parts)

    def sync_all(self, root: Path) -> list[Path]:
        """Sync to all registered targets. Returns list of created paths."""
        content = self.collect()
        paths: list[Path] = []
        for converter in _CONVERTERS:
            path = converter.write(root, content)
            paths.append(path)
        return paths

    def sync(self, root: Path, target: str) -> Path:
        """Sync to a specific target. Returns created path."""
        converter = _CONVERTER_MAP.get(target)
        if converter is None:
            raise ValueError(
                f"Unknown target: '{target}'. "
                f"Available targets: {', '.join(_CONVERTER_MAP)}"
            )
        content = self.collect()
        return converter.write(root, content)
