"""Tests for myxo sync command."""

from pathlib import Path

from typer.testing import CliRunner

from myxo.cli import app

runner = CliRunner()

AUTOGEN_HEADER = "<!-- Auto-generated by myxo sync. Do not edit manually. -->"


def _setup_myxo_dir(base: Path) -> Path:
    """Create a minimal .myxo/ directory with rules.md."""
    myxo = base / ".myxo"
    myxo.mkdir()
    (myxo / "rules.md").write_text("# Project Rules\nBe nice.\n")
    (myxo / "protocols").mkdir()
    return myxo


class TestSyncGeneratesCLAUDEmd:
    """myxo sync should generate CLAUDE.md from .myxo/rules.md."""

    def test_sync_creates_claude_md(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.chdir(tmp_path)
        _setup_myxo_dir(tmp_path)

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        claude_md = tmp_path / "CLAUDE.md"
        assert claude_md.exists()

    def test_sync_includes_rules_content(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.chdir(tmp_path)
        _setup_myxo_dir(tmp_path)

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        content = (tmp_path / "CLAUDE.md").read_text()
        assert "# Project Rules" in content
        assert "Be nice." in content


class TestSyncIncludesProtocols:
    """myxo sync should include .md files from .myxo/protocols/."""

    def test_sync_includes_protocol_files(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.chdir(tmp_path)
        myxo = _setup_myxo_dir(tmp_path)
        (myxo / "protocols" / "code-review.md").write_text(
            "# Code Review\nAlways review PRs.\n"
        )
        (myxo / "protocols" / "testing.md").write_text(
            "# Testing\nWrite tests first.\n"
        )

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        content = (tmp_path / "CLAUDE.md").read_text()
        assert "# Code Review" in content
        assert "Always review PRs." in content
        assert "# Testing" in content
        assert "Write tests first." in content

    def test_sync_ignores_non_md_files_in_protocols(
        self, tmp_path: Path, monkeypatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        myxo = _setup_myxo_dir(tmp_path)
        (myxo / "protocols" / "notes.txt").write_text("should not appear")

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        content = (tmp_path / "CLAUDE.md").read_text()
        assert "should not appear" not in content

    def test_sync_works_without_protocols_dir(
        self, tmp_path: Path, monkeypatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        myxo = tmp_path / ".myxo"
        myxo.mkdir()
        (myxo / "rules.md").write_text("# Rules\n")
        # No protocols/ directory at all

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        assert (tmp_path / "CLAUDE.md").exists()


class TestSyncFailsWithoutMyxoDir:
    """myxo sync should fail if .myxo/ doesn't exist."""

    def test_sync_exits_with_error(self, tmp_path: Path, monkeypatch) -> None:
        monkeypatch.chdir(tmp_path)

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 1
        assert ".myxo" in result.output


class TestSyncAutoGeneratedHeader:
    """Generated CLAUDE.md should have the auto-generated header comment."""

    def test_claude_md_starts_with_header(
        self, tmp_path: Path, monkeypatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        _setup_myxo_dir(tmp_path)

        result = runner.invoke(app, ["sync"])

        assert result.exit_code == 0
        content = (tmp_path / "CLAUDE.md").read_text()
        assert content.startswith(AUTOGEN_HEADER)
