use std::path::{Path, PathBuf};

use crate::config::ConfigError;

const AUTOGEN_HEADER: &str = "<!-- Auto-generated by mxl sync. Do not edit manually. -->";

pub trait Converter {
    fn name(&self) -> &str;
    fn output_path(&self, root: &Path) -> PathBuf;

    fn convert(&self, content: &str) -> String {
        format!("{AUTOGEN_HEADER}\n\n{content}")
    }

    fn write(&self, root: &Path, content: &str) -> Result<PathBuf, ConfigError> {
        let path = self.output_path(root);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| ConfigError::Io {
                path: parent.to_path_buf(),
                source: e,
            })?;
        }
        std::fs::write(&path, self.convert(content)).map_err(|e| ConfigError::Io {
            path: path.clone(),
            source: e,
        })?;
        Ok(path)
    }
}

macro_rules! define_converter {
    ($name:ident, $target:expr, $path:expr) => {
        pub struct $name;
        impl Converter for $name {
            fn name(&self) -> &str {
                $target
            }
            fn output_path(&self, root: &Path) -> PathBuf {
                $path(root)
            }
        }
    };
}

define_converter!(ClaudeConverter, "claude", |root: &Path| root
    .join("CLAUDE.md"));
define_converter!(CodexConverter, "codex", |root: &Path| root
    .join("AGENTS.md"));
define_converter!(CursorConverter, "cursor", |root: &Path| root
    .join(".cursor")
    .join("rules"));
define_converter!(WindsurfConverter, "windsurf", |root: &Path| root
    .join(".windsurfrules"));

fn converters() -> Vec<Box<dyn Converter>> {
    vec![
        Box::new(ClaudeConverter),
        Box::new(CodexConverter),
        Box::new(CursorConverter),
        Box::new(WindsurfConverter),
    ]
}

pub struct MyxoSyncer {
    myxo_dir: PathBuf,
}

impl MyxoSyncer {
    pub fn new(myxo_dir: &Path) -> Self {
        Self {
            myxo_dir: myxo_dir.to_path_buf(),
        }
    }

    pub fn collect(&self) -> Result<String, ConfigError> {
        let rules_path = self.myxo_dir.join("rules.md");
        let mut parts =
            vec![
                std::fs::read_to_string(&rules_path).map_err(|e| ConfigError::Io {
                    path: rules_path,
                    source: e,
                })?,
            ];

        let protocols_dir = self.myxo_dir.join("protocols");
        if protocols_dir.is_dir() {
            let mut entries: Vec<_> = std::fs::read_dir(&protocols_dir)
                .map_err(|e| ConfigError::Io {
                    path: protocols_dir.clone(),
                    source: e,
                })?
                .collect::<Result<Vec<_>, _>>()
                .map_err(|e| ConfigError::Io {
                    path: protocols_dir.clone(),
                    source: e,
                })?
                .into_iter()
                .filter(|e| e.path().extension().is_some_and(|ext| ext == "md"))
                .collect();
            entries.sort_by_key(|e| e.file_name());

            for entry in entries {
                let content =
                    std::fs::read_to_string(entry.path()).map_err(|e| ConfigError::Io {
                        path: entry.path(),
                        source: e,
                    })?;
                parts.push(content);
            }
        }

        Ok(parts.join("\n"))
    }

    pub fn sync(&self, root: &Path, target: &str) -> Result<PathBuf, ConfigError> {
        let all = converters();
        let converter = all.iter().find(|c| c.name() == target).ok_or_else(|| {
            let available: Vec<_> = all.iter().map(|c| c.name()).collect();
            ConfigError::Format(format!(
                "unknown sync target: '{target}'. Available: {}",
                available.join(", ")
            ))
        })?;
        let content = self.collect()?;
        converter.write(root, &content)
    }

    pub fn sync_all(&self, root: &Path) -> Result<Vec<PathBuf>, ConfigError> {
        let content = self.collect()?;
        let mut paths = Vec::new();
        for converter in converters() {
            paths.push(converter.write(root, &content)?);
        }
        Ok(paths)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converter_names() {
        assert_eq!(ClaudeConverter.name(), "claude");
        assert_eq!(CodexConverter.name(), "codex");
        assert_eq!(CursorConverter.name(), "cursor");
        assert_eq!(WindsurfConverter.name(), "windsurf");
    }

    #[test]
    fn converter_output_paths() {
        let root = std::path::Path::new("/repo");
        assert_eq!(ClaudeConverter.output_path(root), root.join("CLAUDE.md"));
        assert_eq!(CodexConverter.output_path(root), root.join("AGENTS.md"));
        assert_eq!(
            CursorConverter.output_path(root),
            root.join(".cursor/rules")
        );
        assert_eq!(
            WindsurfConverter.output_path(root),
            root.join(".windsurfrules")
        );
    }

    #[test]
    fn convert_adds_autogen_header() {
        let output = ClaudeConverter.convert("hello");
        assert!(output.starts_with(AUTOGEN_HEADER));
        assert!(output.contains("hello"));
    }

    #[test]
    fn syncer_collect_reads_rules() {
        let dir = std::env::temp_dir().join("myxo-syncer-test");
        let myxo_dir = dir.join(".myxo-lab");
        std::fs::create_dir_all(&myxo_dir).unwrap();
        std::fs::write(myxo_dir.join("rules.md"), "# Rules\n").unwrap();

        let syncer = MyxoSyncer::new(&myxo_dir);
        let content = syncer.collect().unwrap();
        assert!(content.contains("# Rules"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn syncer_collect_includes_protocols() {
        let dir = std::env::temp_dir().join("myxo-syncer-proto-test");
        let myxo_dir = dir.join(".myxo-lab");
        let protocols_dir = myxo_dir.join("protocols");
        std::fs::create_dir_all(&protocols_dir).unwrap();
        std::fs::write(myxo_dir.join("rules.md"), "# Rules\n").unwrap();
        std::fs::write(protocols_dir.join("a.md"), "# Protocol A\n").unwrap();

        let syncer = MyxoSyncer::new(&myxo_dir);
        let content = syncer.collect().unwrap();
        assert!(content.contains("# Rules"));
        assert!(content.contains("# Protocol A"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn syncer_sync_writes_file() {
        let dir = std::env::temp_dir().join("myxo-syncer-write-test");
        let myxo_dir = dir.join(".myxo-lab");
        std::fs::create_dir_all(&myxo_dir).unwrap();
        std::fs::write(myxo_dir.join("rules.md"), "# Rules\n").unwrap();

        let syncer = MyxoSyncer::new(&myxo_dir);
        let path = syncer.sync(&dir, "claude").unwrap();
        assert_eq!(path, dir.join("CLAUDE.md"));
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with(AUTOGEN_HEADER));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn syncer_sync_unknown_target_fails() {
        let dir = std::env::temp_dir().join("myxo-syncer-unknown-test");
        let myxo_dir = dir.join(".myxo-lab");
        std::fs::create_dir_all(&myxo_dir).unwrap();
        std::fs::write(myxo_dir.join("rules.md"), "# Rules\n").unwrap();

        let syncer = MyxoSyncer::new(&myxo_dir);
        assert!(syncer.sync(&dir, "nonexistent").is_err());

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn syncer_sync_all_creates_all_targets() {
        let dir = std::env::temp_dir().join("myxo-syncer-all-test");
        let myxo_dir = dir.join(".myxo-lab");
        std::fs::create_dir_all(&myxo_dir).unwrap();
        std::fs::write(myxo_dir.join("rules.md"), "# Rules\n").unwrap();

        let syncer = MyxoSyncer::new(&myxo_dir);
        let paths = syncer.sync_all(&dir).unwrap();
        assert_eq!(paths.len(), 4);

        std::fs::remove_dir_all(&dir).ok();
    }
}
